One less pie: Occurrence of lung cancer
========================================================

Setting up the dataframe

```{r}
Cancer_names = c("Squamous Cell Carcinoma", "Small Cell Carcinoma", "AdenoCarcinoma", "Large Cell Carcinoma", "All histological types")
Non_smoker = c(7,2,85,11,105)
Smoker = c(115, 176 , 285, 49, 625)
df_cancer = data.frame(Cancer_names, Non_smoker, Smoker)
df_cancer

```

Getting percent of occurrence

```{r}
library(reshape)
total = df_cancer[[5,2]]+df_cancer[[5,3]]
df_cancer["percent nonsmoker"] = (df_cancer$Non_smoker/total)*100
df_cancer <- rename(df_cancer, c('percent nonsmoker'='pns'))
df_cancer["ps"] = (df_cancer$Smoker/total)*100
df_cancer$Cancer_names = c("Large Cell", "Squamous Cell", "Small Cell", "Adeno", "All histological types")

```
Reshaping the dataframe to use it in ggplot for grouped barplots
```{r}
library(reshape)
melted.df_cancer = melt(df_cancer, id=("Cancer_names"))
melted.df_cancer2 = subset(melted.df_cancer, variable == "ps" | variable == "pns")
melted.df_cancer2$Cancer_names <- factor(melted.df_cancer2$Cancer_names, levels = c("Large Cell", "Squamous Cell", "Small Cell" , "Adeno", "All histological types"))
```
Plotting the grouped barplot
```{r fig.width=7, fig.height=6}
library(ggplot2)
str = "Percentage of incidence for different histological types of lung cancer \n for smokers and non-smokers"
ggplot(melted.df_cancer2, stat="identity", aes(x=Cancer_names, y= value, fill = variable))+geom_bar(position="dodge")+xlab(" Types of Lung Cancer")+ ylab("Percentage of incidence") + ggtitle(str)+scale_y_continuous(breaks = round(seq(0, max(melted.df_cancer2$value), by = 20),1))
```

